"""Filesystem paths for the data layer.

The processed/raw data directories are gitignored (CLAUDE.md §3): generated
Parquet is regenerated by the ingestion script, never committed.
"""

from __future__ import annotations

from pathlib import Path

# .../quant_backtest/config/paths.py -> parents[2] == project root.
PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]

DATA_DIR: Path = PROJECT_ROOT / "data"
RAW_DIR: Path = DATA_DIR / "raw"
PROCESSED_DIR: Path = DATA_DIR / "processed"


def ensure_dirs() -> None:
    """Create the raw/processed data directories if they do not exist.

    Called at ingestion time (not at import time) so importing config has no
    filesystem side effects.
    """
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
